## 12 通过异常处理错误
基本理念：结构不佳的代码不能运行。

异常处理是Java中唯一正式的错误报告机制，并且通过编译器强制执行。

### 12.2 基本异常
异常情形：是指组织当前方法或作用域继续执行的问题

当抛出异常时，有几件事随之发生：
1. 使用new在堆上创建异常对象
1. 当前的执行路径被终止，并且从当前环境中弹出对异常对象的引用
1. 此时，异常处理机制接管程序，并开始寻找一个*恰当的地方*（即**异常处理程序**）来继续执行程序。

例子：
```
if (t == null)
    throw new NullPointerException();
```
抛出一个异常，则在当前环境下就不必再为这个问题操心，它将在别的地方得到处理。

异常使得我们可以将每件事都当作一个事务来考虑，而异常可以看护着这些事务的底线。
我们可以把异常看作一个内建的恢复（undo）系统，因为我们在程序中可以拥有各种不同的恢复点。如果程序某部分失败了，异常将“恢复”到程序中某个已知的稳定点上。
异常最重要的方面之一就是：如果发生问题，他们将不允许程序沿着正常的路径继续走下去。

#### 12.2.1 异常参数
标准异常类都有两个构造器：默认构造器、接受字符串作为参数的构造器。

能够抛出任意类型的Throwable对象，是异常类型的根类。

### 12.3 捕获异常
#### 12.3.1 try块
不希望方法在抛出异常的过程中结束，可以设置try块来捕获异常。

#### 12.3.2 异常处理程序
异常处理程序紧跟在try块之后，以关键字catch表示。每个catch字句接收一个且仅接收一个异常类型。当异常被抛出时，只有匹配的catch字句才能得到执行。

### 12.4 创建自定义异常
要自己定义异常类，必须从已有的异常类继承，最好是选择意思相近的异常类继承。

#### 12.4.1 异常与记录日志
使用``java.util.logging``工具将输出记录到日志中。
```
private static Logger logger = Logger.getLogger("LoggingException");
StringWriter trace = new StringWriter();
printStackTrace(new Printer(trace));
logger.severe(trace.toString());
```

### 12.5 异常说明
告知某个方法可能会抛出的异常类型。使用关键字 ``throws``：
```
void f() throws TooBig, TooSmall, DivZero { //
```

### 12.6 捕获所有异常
通过捕获异常类型的基类``Exception``就可以捕获所有异常：
```
catch(Exception e) {
    ...;
}
```

可以调用它从其基类``Throwable``继承的方法：
```
String getMessage()
String getLocalizedMessage()
String toString()
void printStackTrace()
void printStackTrace(PrintStream)
void printStackTrace(java.io.PrintWriter)
...
```

也可以调用它从更基类``Object``继承的方法：``getClass()``, ``getName()``, ``getSimpleName()``...

#### 12.6.1 栈轨迹
``getStackTrace()``方法返回一个由栈轨迹中的元素所构成的数组。
- 元素0是栈顶元素，是调用序列中的最后一个方法调用
- 最后一个元素时栈底元素，是调用序列中的第一个方法调用

#### 12.6.2 重新抛出异常
##### 情况1：直接重新抛出异常
```
catch(Exception e) {
    throw e;
}
```
把异常抛给**上一级**环境中的异常处理程序。异常对象中的所有信息都得以保持。``printStackTrace()``方法显示的是原来异常抛出点的调用栈信息。可以调用``fillInStackTrace()``方法来更新信息：
``throw (Exception)e.fillInStackTrace()``，则自己下一级的异常信息不会保留，仅从自己这级往上。

例如：
- g()中调用f，``throw e``，则main的输出为：
```
thrown from f()
at f
at g
at main
```
- h()中调用f，``throw (Exception)e.fillInStackTrace()``，则main的输出为：
```
thrown from f()
at h
at main
```

##### 情况2：在捕获异常后抛出另一种异常
效果类似于``fillInStackTrace()``，有关原来异常发生点的信息会丢失

#### 12.6.3 异常链
在捕获一个异常后抛出另一个异常，并且希望把原始异常的信息保存下来。
```
try {
    result = getField(id);
} catch (NoSuchFieldException e) {
    throw new RuntimeException(e);
}
```
即：在catch块中重新throw一个新的Exception。


### 12.7 Java标准异常
``Throwable``类被用来表示任何可以作为异常被抛出的类：
- Error用来表示编译时和系统错误
- Exception是可以被抛出的基本类型
    - 在Java类库、用户方法以及运行时故障中都可能抛出Exception型异常，所以关心的基类型通常是Exception

#### 12.7.1 特例：RuntimeException
属于运行时异常的类型有很多，它们会自动被Java虚拟机抛出，所以不必在异常说明中把他们列出来。
这些异常都从RuntimeException类继承而来。

不再需要在异常说明中声明方法将抛出RuntimeException类型的异常，因为这类异常将被自动捕获。如果没有手动捕获，这类异常将直达``main()``，并在程序退出前调用``printStackTrace()``方法。

只能在代码中忽略RuntimeException（及其子类）类型的异常，其他类型异常处理都是由编译器强制实施的。

### 12.8 使用finally进行清理
无论try块中的异常是否抛出，finally块中的代码都能得到执行。这通常适用于内存回收之外的情况（因为回收由垃圾回收器完成）。

思路：
- 把try块放在循环里，就建立了一个”程序继续执行之前必须要达到“的条件。
- 加入一个static类型的计数器或者别的装置，使循环在放弃以前能尝试一定的次数。

#### 12.8.1 finally用来做什么
当要把**内存之外**的资源恢复到它们的初始状态时，就要用到finally字句。
- 已经打开的文件或网络连接
- 在屏幕上画的图形
- 外部世界的某个开关……

#### 12.8.2 在return中使用finally
因为finally字句总是会执行的，所以在一个方法中，可以从多点返回，对finally的执行无关紧要。

#### 12.8.3 遗憾：异常丢失
- 如果``finally``块中也抛出异常，它会取代``try``块中抛出的异常。
- 如果从``finally``块中返回，``try``块中抛出的异常也不会产生任何输出。

### 12.9 异常的限制
- 当覆盖方法的时候，**只能**抛出在**基类方法**的异常说明里列出的那些异常。
    - 所以在基类声明时声明抛出异常但实际上没抛出，这种方式使你能够强制用户去捕获可能在覆盖后的方法版本中增加的异常。
    - 当然，基类声明抛出的异常，并不强制导出类也声明抛出。
- 如果是导出类的新方法，则异常类型无限制。
- 异常限制对构造器不起作用。构造器可以跑出任何异常，但必须包含基类构造器的异常说明。
- 在``main()``中，如果处理的刚好是导出类对象的话，编译器只会强制要求捕获这个类所抛出的异常。但如果向上转型为基类，那么编译器就会要求你捕获基类的异常。

### 12.10 构造器
问题：如果够再起在其执行过程中半途而废，也许该对象的某些部分还没有被成功创建，而这些部分在finally字句中确实要被清理的。

例如：如果打开文件，抛出``FileNotFoundException``，则不需要关闭文件；而如果抛出其它异常，则说明文件已经打开，需要关闭文件。
而``close()``方法也会抛出异常，因此内层还需要再用一层``try-catch``来关闭文件。

对于在构造阶段可能会抛出异常，并且要求清理的类，最安全的使用方式是使用嵌套的try字句。
基本规则：在创建需要清理的对象之后，立即进入一个try-finally语句块。

### 12.11 异常匹配
抛出异常的时候，异常处理系统会按照代码的书写顺序找出”最近“的处理程序。找到匹配的处理程序之后，它就认为异常将得到处理，然后就不再继续查找。
查找的时候并不要求抛出的异常和处理程序声明的异常完全匹配。派生异常类的对象也可以匹配基异常类的处理程序。

### 12.13 异常使用指南
1. 在恰当的级别处理问题（在知道该如何处理的情况下才捕获异常）
1. 解决问题并且重新调用产生异常的方法
1. 进行少许修补，然后绕过异常发生的地方继续执行
1. 用别的数据进行计算，以代替方法预计会返回的值
1. 把当前运行环境下能做的事尽量做完，然后把相同的异常重抛到更高层
1. 把当前运行环境下能做的事情尽量做完，然后把不同的异常抛到更高层
1. 终止程序
1. 进行简化
1. 让类库和程序更安全
